version: '3.8'

services:
  quillium:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - AI_ENDPOINT=https://api.openai.com/v1
      # Uncomment and set your API key
      # - API_KEY=your_api_key_here
      - DB_PATH=/app/data/quillium.db
    restart: unless-stopped
