version: '3.8'

services:
  test-db:
    image: postgres:17
    container_name: quillium-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quillium_test
    ports:
      - "5432:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Add extra_hosts to support host.docker.internal on all platforms
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  test-db-data:
