name: Update Contributors

on:
  workflow_dispatch: # Allows manual triggering
  issues:
    types: [closed]
  pull_request:
    types: [closed]
  push:
    branches: [main, master]

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions: # Add write permission
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: all-contributors/github-action@v2
        with:
          auto: true
          configPath: .all-contributorsrc # Corrected property name
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
