name: Update Contributors
on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]
  push:
    branches: [main, master]

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: all-contributors/github-action@v2
        with:
          # Auto-detect contributions from PRs/issues
          auto: true
          # Configuration file path (default shown)
          config: .all-contributorsrc
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
