name: Update Contributors
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'  # Daily at 12PM UTC
  workflow_dispatch:

permissions:
  contents: write  # Required for committing changes

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full git history

      - name: Update contributors
        uses: all-contributors/all-contributors-bot@v1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          config-path: .all-contributorsrc  # Explicit path to your config
          skip-ci: true  # Matches your config
