name: Update Contributors
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - uses: JoshuaKGoldberg/all-contributors-auto-action@v0.3.2
        name: Update contributors
        with:
          token: ${{ secrets.PAT }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
