name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for commit history analysis

      - name: Update contributors
        uses: all-contributors/app-action@v1.0.4  # Correct action reference
        with:
          command: auto
          args: --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "docs: update contributors list"
          title: "📚 Update contributors list"
          branch: update-contributors
          base: main
