name: Update Contributors
on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12PM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main  # Check out the protected branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install all-contributors-cli
        run: npm install -g all-contributors-cli

      - name: Generate contributors
        run: |
          npx all-contributors check
          npx all-contributors generate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "update-contributors"  # Unique branch name
          commit-message: "docs: Update contributors list"
          title: "📌 Update contributors list"
          body: "Automated update of contributors list"
          base: main  # Target protected branch
          delete-branch: true  # Clean up after merge
          token: ${{ secrets.PAT }}
