name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install all-contributors-cli
        run: npm install --no-save all-contributors-cli@6.18.0

      - name: Identify and add new contributors
        run: |
          # Check for new contributors not yet added
          missing_contributors=$(npx all-contributors check | grep 'Missing contributors:' | sed 's/Missing contributors: //')
          
          if [ -n "$missing_contributors" ]; then
            for contributor in $missing_contributors; do
              # Add each missing contributor with a default contribution type
              npx all-contributors add $contributor code
            done
            # Generate the updated contributors list
            npx all-contributors generate
          else
            echo "No new contributors to add."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: "docs(contributors): update contributors list"
          title: "Update contributors list"
          body: |
            Automated update of contributors list by GitHub Actions.

            **Changes:**
            - Updated CONTRIBUTORS.md with new contributors.
          branch: update-contributors
          base: main
          author: github-actions <github-actions@github.com>
