update-contributors:
  stage: deploy
  image: node:20
  variables:
    GIT_AUTHOR_NAME: "Hadi Cherkaoui"
    GIT_AUTHOR_EMAIL: "github@hide.cherkaoui.ch"
    GIT_COMMITTER_NAME: "Hadi Cherkaoui"
    GIT_COMMITTER_EMAIL: "github@hide.cherkaoui.ch"
  script:
    - npm install -g all-contributors-cli

    # Extract the line with missing contributors
    - MISSING_LINE=$(npx all-contributors check | awk '/Missing contributors/{getline; print}')
    # Split on commas and process each username robustly
    - |
      IFS=',' read -ra USERS <<< "$MISSING_LINE"
      for username in "${USERS[@]}"; do
        username=$(echo "$username" | xargs)  # Trim whitespace
        [ -z "$username" ] && continue
        case "$username" in
          dependabot[bot]|github-actions[bot]|Devin-create)
            echo "Skipping excluded user: $username"
            continue
            ;;
        esac
        # Check if user exists on GitLab using CI_JOB_TOKEN
        if curl --silent --header "JOB-TOKEN: $CI_JOB_TOKEN" \
            "$CI_API_V4_URL/users?username=$username" | grep -q "\"username\":\"$username\""; then
          echo "Adding contributor: $username"
          npx all-contributors add "$username" code
        else
          echo "User $username does not exist on GitLab, skipping."
        fi
      done

    # Generate final output
    - npx all-contributors generate

    # Create MR if there are changes
    - |
      if [[ -n $(git status -s) ]]; then
        git checkout -b update-contributors
        git add .
        git commit -m "docs: Update contributors list"
        git push -f origin update-contributors
        echo "Creating merge request..."
        curl --request POST \
          --header "JOB-TOKEN: $CI_JOB_TOKEN" \
          --header "Content-Type: application/json" \
          --data '{
            "source_branch": "update-contributors",
            "target_branch": "main",
            "merge_when_pipeline_succeeds": true,
            "should_remove_source_branch": true,
            "title": "📌 Update contributors",
            "description": "Automatically added missing contributors"
          }' \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/merge_requests"
      else
        echo "No changes to commit"
      fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
